package com.test.demo.utility;

import javax.validation.ConstraintViolationException;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;

import com.test.demo.dtos.response.ResponseDto;

@ControllerAdvice
public class ApiExceptionHandler {

	@ExceptionHandler(value = {IllegalArgumentException.class, UsernameNotFoundException.class, ConstraintViolationException.class})
    public ResponseEntity<ResponseDto> handle(Exception e) {
        var response = new ResponseDto();
        response.setMessage(e.getCause().toString());
        response.setStatusCode(HttpStatus.BAD_REQUEST.toString());
        errors.addError("Error", message);
        return new ResponseEntity<>(errors, HttpStatus.BAD_REQUEST);
    }
    @ExceptionHandler
    public ResponseEntity<ResponseDto> handleAnyException(Exception e) {
        var response = new ResponseDto();
        response.setMessage(e.getMessage());
        response.setStatusCode(HttpStatus.INTERNAL_SERVER_ERROR.toString());
        return new ResponseEntity<>(response, HttpStatus.INTERNAL_SERVER_ERROR);
    }
    

   
}
